services:
    admin.config:
        class: Biopen\CoreBundle\Admin\ConfigurationAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Configuration", label: Configuration Générale }

    admin.home_config:
        class: Biopen\CoreBundle\Admin\ConfigurationHomeAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Configuration", label: Page d'accueil }

    admin.map_config:
        class: Biopen\CoreBundle\Admin\ConfigurationMapAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Configuration", label: La carte }

    admin.form_config:
        class: Biopen\CoreBundle\Admin\ConfigurationFormContributionsAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Configuration", label: Formulaire / Contributions }

    admin.style_config:
        class: Biopen\CoreBundle\Admin\ConfigurationStyleAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Configuration", label: Style }

    admin.mail_config:
        class: Biopen\CoreBundle\Admin\ConfigurationMailAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Configuration", label: Mails / Newsletter }

    admin.feature_config:
        class: Biopen\CoreBundle\Admin\FeatureConfigurationAdmin
        arguments: [~, Biopen\CoreBundle\Document\FeatureConfiguration, '']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }

    admin.interaction_config:
        class: Biopen\CoreBundle\Admin\InteractionConfigurationAdmin
        arguments: [~, Biopen\CoreBundle\Document\InteractionConfiguration, '']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }

    admin.automated_mail_config:
        class: Biopen\CoreBundle\Admin\AutomatedMailConfigurationAdmin
        arguments: [~, Biopen\CoreBundle\Document\AutomatedMailConfiguration, '']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }

    admin.tile_layer:
        class: Biopen\CoreBundle\Admin\TileLayerAdmin
        arguments: [~, Biopen\CoreBundle\Document\TileLayer, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Configuration", label: Fonds de carte }

    admin.about:
        class: Biopen\CoreBundle\Admin\AboutAdmin
        arguments: [~, Biopen\CoreBundle\Document\About, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenus", label: Onglets "A propos" }
    
    admin.partner:
        class: Biopen\CoreBundle\Admin\PartnerAdmin
        arguments: [~, Biopen\CoreBundle\Document\Partner, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenus", label: Qui sommes nous }
    
    admin.parter_image:
        class: Biopen\CoreBundle\Admin\ImageAdmin
        arguments: [~, Biopen\CoreBundle\Document\PartnerImage, '' ]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }   

    admin.conf_image:
        class: Biopen\CoreBundle\Admin\ImageAdmin
        arguments: [~, Biopen\CoreBundle\Document\ConfImage, '' ]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }   

    admin.wrapper:
        class: Biopen\CoreBundle\Admin\WrapperAdmin
        arguments: [~, Biopen\CoreBundle\Document\Wrapper, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenus", label: Bandeaux de la page d'accueil }

    admin.image:
        class: Biopen\CoreBundle\Admin\ImageAdmin
        arguments: [~, Biopen\CoreBundle\Document\EmbeddedImage, '' ]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" } 


    