imports:
    - { resource: parameters.yml }
    - { resource: version.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: services_admin.yml }
    - { resource: config_fosuser.yml }
    - { resource: config_sonata.yml }
    - { resource: "@BiopenCoreBundle/Resources/config/services.yml" }
    - { resource: "@BiopenGeoDirectoryBundle/Resources/config/services.yml" }
    - { resource: "@SonataUserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    mongodb_server: "mongodb://localhost:27017"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: %csrf_protection%
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ['127.0.0.1']
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    globals:
        version: '%app.version%'
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../src/Biopen/GeoDirectoryBundle/Resources/views": BiopenGeoDirectory
        "%kernel.root_dir%/../src/Biopen/GeoDirectoryBundle/Resources/views/admin": BiopenAdmin
        "%kernel.root_dir%/../src/Biopen/CoreBundle/Resources/views": BiopenCoreBundle
        "%kernel.root_dir%/../src/Application/Sonata/UserBundle/Resources/views": UserBundle
        "%kernel.root_dir%/../web": RootDir
    form_themes:
        - 'SonataFormatterBundle:Form:formatter.html.twig'
    form:
        resources:
            - 'SonataCoreBundle:Form:colorpicker.html.twig'
            - 'XmonColorPickerTypeBundle:Form:fields.html.twig'
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        
# Mongodb Configuration
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    default_database: gogocarto
    document_managers:
        default:
            auto_mapping: true
            mappings:                  
                # gedmo_translatable:
                #     type: annotation
                #     prefix: Gedmo\Translatable\Document
                #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Document"
                #     alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                #     is_bundle: false
                # gedmo_translator:
                #     type: annotation
                #     prefix: Gedmo\Translator\Document
                #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Document"
                #     alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                #     is_bundle: false
                gedmo_loggable:
                    type: annotation
                    prefix: Gedmo\Loggable\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Document"
                    alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                    is_bundle: false
                # gedmo_tree:
                #     type: annotation
                #     prefix: Gedmo\Tree\Document
                #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Document"
                #     alias: GedmoTree # (optional) it will default to the name set for the mapping
                #     is_bundle: false

fos_js_routing:
    routes_to_expose: []

stof_doctrine_extensions:
    default_locale: fr
    mongodb:
        default:
            sortable: true
            loggable: true
            sluggable: true
            timestampable: true

pix_sortable_behavior:
    db_driver: mongodb 
    position_field:
        default: position 
        entities:
            Biopen\GeoDirectoryBundle\Document\Option: index
            Biopen\GeoDirectoryBundle\Document\Category: index

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: ssl
    port : 465
    auth_mode : login
    # spool:     { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        #     formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        # sass:    ~
        # compass: ~
        # uglifycss:
        #     bin: C:/users/MARIETTE/AppData/Roaming/npm/uglifycss

bazinga_geocoder: 
    providers:
        google_maps:
            locale:               fr
            region:               null
            use_ssl:              true
            api_key:              AIzaSyBgah9u8A21CdN6O_fN80Op-4zcLJ0EwXk
        openstreetmap:
            locale:               fr


ivory_ck_editor:
    default_config: full
    configs:
        full:
            toolbar:
            - [ - , NumberedList, BulletedList, -, Outdent, Indent ]
            - [ Image, Link, Unlink, Table , Blockquote, HorizontalRule, Iframe ]
            - -
            - [ Cut, Copy, Paste, PasteText, PasteFromWord, -, Undo, Redo ]
            - [ -,Maximize, ShowBlocks, Source ]            
            - /
            - [ Bold, Italic, Underline, Strike, -, RemoveFormat ]
            - [ -, Styles,Format,Font,FontSize, TextColor, BGColor]
            - [ -, JustifyLeft,JustifyCenter,JustifyRight,JustifyBlock]

vich_uploader:
    db_driver: mongodb

    mappings:
        import_file:
            uri_prefix: /imports
            upload_destination: '%kernel.root_dir%/../web/uploads/imports'
            
            
            
            