# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    my_user_provider.class: Application\Sonata\UserBundle\Security\FOSUBUserProvider

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.sortbyfield:
        class: Snilius\Twig\SortByFieldExtension
        tags:
            - { name: twig.extension }
    admin.about:
        class: Biopen\CoreBundle\Admin\AboutAdmin
        arguments: [~, Biopen\CoreBundle\Document\About, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenus", label: Onglets "A propos" }
    admin.partner:
        class: Biopen\CoreBundle\Admin\PartnerAdmin
        arguments: [~, Biopen\CoreBundle\Document\Partner, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenus", label: Partenaires }
    admin.wrapper:
        class: Biopen\CoreBundle\Admin\WrapperAdmin
        arguments: [~, Biopen\CoreBundle\Document\Wrapper, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenus", label: Bandeaux de la page d'accueil }

    admin.element:
        class: Biopen\GeoDirectoryBundle\Admin\ElementAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Element, 'BiopenGeoDirectoryBundle:ElementAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Annuaire", label: Acteurs }

    admin.category:
        class: Biopen\GeoDirectoryBundle\Admin\CategoryAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Category, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Annuaire", label: Cat√©gories }

    admin.option:
        class: Biopen\GeoDirectoryBundle\Admin\OptionAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Option, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Annuaire", label: Options }

    sonata.block.service.monitoring:
        class: Biopen\GeoDirectoryBundle\Block\MonitoringElementsBlockService
        arguments: [ @templating, @doctrine.odm.mongoDB.document_manager ]
        tags:
            - { name: sonata.block }

    biopen.block.recent_elements:
        class: Biopen\GeoDirectoryBundle\Block\RecentElementsBlockService
        arguments: [ @templating, @doctrine.odm.mongoDB.document_manager, @sonata.admin.pool ]
        tags:
            - { name: sonata.block }

    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebookUid, gplus: gplusUid, yahoo: twitterUid}]

    biopen.authentication_handler:
        class: Application\Sonata\UserBundle\Security\AuthenticationHandler
        public: false
        arguments:
            - @router
            - @session

    biopen.registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: biopen_user_registration }