biopen_element_add:
    path:     /add
    defaults: { _controller: BiopenGeoDirectoryBundle:ElementForm:add }

biopen_element_edit:
    path:     /edit/{id}
    defaults: { _controller: BiopenGeoDirectoryBundle:ElementForm:edit }
    options:
        expose: true

biopen_element_check_duplicate:
    path:     /check-doublons
    defaults: { _controller: BiopenGeoDirectoryBundle:ElementForm:checkDuplicates }

biopen_element_delete:
    path:     /delete/{id}
    defaults: { _controller: BiopenGeoDirectoryBundle:ElementForm:delete }

biopen_element_generate:
    path:     /generate/{nombre}/{generateVotes}
    defaults: { _controller: BiopenGeoDirectoryBundle:Import:generateRandom, nombre:'1', generateVotes:'0' }




