biopen_element:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-element-form.yml"
    prefix:   /elements

biopen_directory:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-directory.yml"

biopen_import:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-import.yml"
    prefix:   /admin/import

biopen_api:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-api.yml"
    prefix:   /api

biopen_vote:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-element-interaction.yml"
    prefix: /interact

biopen_bulk_actions:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-bulk-actions.yml"
    prefix: /admin/bulkActions

biopen_duplicates:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing-duplicates.yml"
    prefix: /duplicates

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"